### ISSUE TITLE
spacepy expects to write to the $HOME directory, thus breaking spacepy based das2 CDF readers.

### ISSUE THREAD

**Issue by cpiker** [das-developers/das2-pyserver#2]
CDF based das2 readers relying on spacepy.pycdf expect to write to their home directory, which fails for web-services.  Maybe providing a standalone pycdf as part of das2py is a solution.

**Comment by BaptisteCecconi** [comment]
I think we have similar issues in `maser4py`, and we have extracted the `pycdf` module. There should be some coordination with `spacepy` for the future, to make sure that the library runs in all conditions. 

By the way, if you create the required directory in the `www-data` (for debian, it is `/var/www`) $HOME directory, it may work.

**Comment by cpiker** [comment]
The pycdf module is so generically useful that would be handy to have a centrally maintained standalone version that is not part of spacepy.  Preferably someone with spacepy or cdaweb would maintain it.  Otherwise many different space physics libraries are going to carry around their own version of pycdf, which is probably not optimal.

**Comment by cpiker** [comment]
The dependency on spacepy has been removed, closing the issue.
