### ISSUE TITLE
HAPI support not working with python3 install

### ISSUE THREAD

**Issue by BaptisteCecconi** [das-developers/das2-pyserver#6]
I've activated HAPI on a Python3 installation. The `HAPI` landing page works, but the sub-pages (`capabilities`, `catalog`...) are broken. 

The error is 
```
Error loading module catalog from das2server.h_api: No module named 'error'
```

For reference, the `util` module is working, so there should be a way to make `h_api` work.

**Comment by cpiker** [comment]
Issue looks to be resolved.  HAPI support tested under python 3.6 and 2.7.

**Warning** A fix was required in das2py.  If you'd like to avoid reinstalling das2py, you can patch instead by copying: [dastime.py](https://raw.githubusercontent.com/das-developers/das2py/master/das2/dastime.py) to your pyserver lib/pythonX.X/das2 directory.
